<div style='color:white; background:black; font-weight: bold; padding:15px,15px,15px,15px; font-size: 30px; text-align: center'>Теория</div>

<div style='text-align: center;font-size: 28px;font-weight: bold; color:blue'>Виды машинного обучения</div>

![Виды машинного обучения](img/kinds_ml.png)

<div style='text-align: center;font-size: 28px;font-weight: bold; color:blue'>Регрессия</div>

![Виды машинного обучения](img/task_regression.png)

<div style='text-align: center;font-size: 28px;font-weight: bold; color:blue'>Классификация</div>

![Виды машинного обучения](img/task_classification.png)

<div style='text-align: center;font-size: 28px;font-weight: bold; color:blue'>Кластеризация</div>

![Виды машинного обучения](img/task_classterization.png)

<div style='text-align: center;font-size: 28px;font-weight: bold; color:blue'>Функции потерь</div>

<div style='text-align: center;font-size: 22px;font-weight: bold; color:red'>Mean squared error (MSE) - регрессия</div>

![MSE](img/mse.png)

<div style='text-align: center;font-size: 22px;font-weight: bold; color:red'>LogLoss - классификация</div>

![Виды машинного обучения](img/logloss.png)

<div style='color:white; background:black; font-weight: bold; padding:15px,15px,15px,15px; font-size: 30px; text-align: center'>Практика</div>

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import make_regression, make_classification
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix


### Генерация выборки

In [2]:
features, output, coef = make_regression(n_samples = 10000, #количество элементов
                                         n_features = 5, #количество признаков
                                         n_informative = 4, #количество информативных признаков
                                         n_targets = 1, #количество целевых признаков
                                         noise = 0, #шум
                                         coef = True)

X = pd.DataFrame(features, columns=['Фактор_1', 'Фактор_2', 'Фактор_3', 'Фактор_4', 'Фактор_5'])
y = pd.DataFrame(output, columns=['Результат'])

df = pd.concat([X, y], axis = 1)

In [3]:
classification_data, classification_labels = make_classification(n_samples=500, #количество элементов
                                                      n_features=5, #количество признаков
                                                      n_informative=4, #количество информативных признаков
                                                      n_classes=2, #количество классов
                                                      n_redundant=0, #количество избыточных признаков
                                                      random_state=23) #возможность генерировать одинаковые выборки


### Небольшое повторение

In [4]:
for index, row in df.iterrows():
    if row["Фактор_1"] >= 3:
        print(f"На строке {index} значение Фактора 1 больше или равно 3")
        
    elif row["Фактор_1"] < -3:
        print("break")
        break
        
    elif row["Фактор_1"] != 1:
        continue  
        
    else:
        pass
        print("pass")

break


### Предварительная обработка данных

In [5]:
df.describe()

Фактор_1      Фактор_2      Фактор_3      Фактор_4      Фактор_5  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean      -0.004767     -0.010539      0.013227     -0.013544      0.002263   
std        0.996650      0.995168      1.003157      0.993141      1.002055   
min       -3.694216     -4.488351     -4.290500     -3.683090     -3.766115   
25%       -0.679403     -0.683971     -0.652861     -0.674589     -0.669907   
50%       -0.009961     -0.010542      0.015599     -0.010625      0.009703   
75%        0.664969      0.673720      0.698109      0.652743      0.655830   
max        3.550831      4.270270      4.032198      4.367216      4.005923   

          Результат  
count  10000.000000  
mean      -0.969915  
std      116.839847  
min     -542.579750  
25%      -79.600213  
50%       -0.540595  
75%       78.448637  
max      441.086357

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Фактор_1   10000 non-null  float64
 1   Фактор_2   10000 non-null  float64
 2   Фактор_3   10000 non-null  float64
 3   Фактор_4   10000 non-null  float64
 4   Фактор_5   10000 non-null  float64
 5   Результат  10000 non-null  float64
dtypes: float64(6)
memory usage: 468.9 KB


In [7]:
df.iloc[1,2] = np.NaN
df.iloc[1,3] = np.NaN
df.iloc[2,4] = np.NaN

In [8]:
df.head()

Фактор_1  Фактор_2  Фактор_3  Фактор_4  Фактор_5   Результат
0  0.721208  0.291442  0.583870  0.243701 -0.767147   72.363231
1 -2.252508 -0.167895       NaN       NaN -0.494869  -60.670144
2 -1.013297 -1.256873 -0.106497  0.635093       NaN  -95.014729
3  0.392441 -0.282610 -0.053886  0.260777  0.347205  -14.366750
4  1.241075  0.658009  0.111451  1.676325 -1.443953  154.075072

In [9]:
df["Фактор_5"] = df["Фактор_5"].fillna(0)
df["Фактор_3"] = df["Фактор_3"].fillna(df["Фактор_3"].mean())
df["Фактор_4"] = df["Фактор_4"].fillna(df["Фактор_4"].median())

In [10]:
df.head()

Фактор_1  Фактор_2  Фактор_3  Фактор_4  Фактор_5   Результат
0  0.721208  0.291442  0.583870  0.243701 -0.767147   72.363231
1 -2.252508 -0.167895  0.013261 -0.010351 -0.494869  -60.670144
2 -1.013297 -1.256873 -0.106497  0.635093  0.000000  -95.014729
3  0.392441 -0.282610 -0.053886  0.260777  0.347205  -14.366750
4  1.241075  0.658009  0.111451  1.676325 -1.443953  154.075072

### Построение модели регрессии

In [11]:
model = LinearRegression()

In [12]:
model.fit(X, y)

LinearRegression()

In [13]:
model.coef_

array([[ 4.48397552e+00,  9.22973464e+01,  5.19125848e+01,
         4.89117137e+01, -7.10542736e-15]])

In [14]:
print(model.coef_[0][0])
print(model.coef_[0][1])
print(model.coef_[0][2])
print(model.coef_[0][3])
print(model.coef_[0][4])

4.483975515887023
92.29734640946461
51.91258484109535
48.911713688397775
-7.105427357601002e-15


In [15]:
coef

array([ 4.48397552, 92.29734641, 51.91258484, 48.91171369,  0.        ])

In [16]:
model.predict([[1,1,1,1,1]])

array([[197.60562045]])

### Построение модели классификации

In [17]:
model = LogisticRegression()

In [18]:
model.fit(classification_data, classification_labels)

LogisticRegression()

In [19]:
model.coef_

array([[-1.27257875,  0.14133928,  1.09158098,  1.07917765,  0.41005178]])

In [20]:
print(model.coef_[0][0])
print(model.coef_[0][1])
print(model.coef_[0][2])
print(model.coef_[0][3])
print(model.coef_[0][4])

-1.2725787495313632
0.14133927753322828
1.0915809800274314
1.0791776477235466
0.41005178447339496


In [21]:
classification_data

array([[-3.67566532,  1.43280426, -3.2429289 ,  0.03384957,  0.21445597],
       [-1.88805125,  0.34579464, -1.12421301, -2.02034321, -1.27646763],
       [-1.1171786 ,  1.03383845, -2.72285658,  3.12372892, -1.25783655],
       ...,
       [-0.22826457, -0.33117903,  0.5864643 ,  0.82759742, -1.53438193],
       [-2.73572828, -0.11190976,  1.45247929, -2.82114298,  0.20448847],
       [-0.09801648, -1.52171115,  1.64739356,  0.14739146,  1.70819623]])

In [22]:
classification_labels

array([1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,

In [23]:
model.predict([[1,1,1,1,1]])

array([1])

### Самостоятельный кейс №1

- Сгенерируйте выборку для регрессии, содержащую 15000 элементов, 5 информативных признаков, 4 неинформативных признака.
- Добавьте шум равный 1.
- Постройте модель линейной регрессии и оцените значение целевого признака для примера, содержащего только 0.
- Подумайте, на какие показатели мог повлиять добавляемый шум.

### Домашняя работа №1

In [24]:
features, output, coef = make_regression(n_samples = 15000, 
                                         n_features = 9, 
                                         n_informative = 4, 
                                         n_targets = 1, 
                                         noise = 1, 
                                         coef = True)

In [25]:
X = pd.DataFrame(features, columns=[f'Признак_{n}' for n in range(1, 10)])
X.head()

Признак_1  Признак_2  Признак_3  Признак_4  Признак_5  Признак_6  \
0  -0.283378   0.616652   0.211588   1.549045   0.255843   0.210986   
1   1.507203  -0.258372   0.546736  -0.157540   0.622998   1.100814   
2  -0.800042   1.074761   0.821412  -0.144543  -1.922967  -0.727108   
3  -0.866143  -1.200794  -1.244995  -0.444248  -0.514361   1.517714   
4  -0.066316  -0.973918  -0.630449  -0.906616  -1.239555  -1.653993   

   Признак_7  Признак_8  Признак_9  
0   0.767309  -0.593328   0.946092  
1   0.006358   0.193451  -0.554567  
2   1.035078   0.142251   1.728228  
3  -0.667133  -1.046214  -0.126269  
4  -1.976440  -0.546609  -0.080369

In [26]:
y = pd.DataFrame(output, columns=['Цель'])
y.head()

Цель
0 -17.659089
1  41.336933
2  16.904596
3 -96.248048
4 -46.167307

In [27]:
model = LinearRegression()
model.fit(features, output)

LinearRegression()

In [28]:
model.coef_

array([ 2.04773592e+01,  1.68113742e+01,  1.28392363e+01, -1.72713045e-03,
        3.73858145e-03, -2.97485593e-03, -6.78677600e-03,  3.94897021e+01,
        5.07765136e-03])

In [29]:
for i in range(len(model.coef_)):
    print(model.coef_[i])

20.477359165371134
16.811374229237785
12.83923626297637
-0.0017271304453014835
0.0037385814504506953
-0.0029748559261211227
-0.006786776001211692
39.489702051052035
0.005077651358731394


In [30]:
# коэффициенты при генерации выборок
coef

array([20.46484186, 16.80955438, 12.84364742,  0.        ,  0.        ,
        0.        ,  0.        , 39.50445653,  0.        ])

In [31]:
model.predict([[0, 0, 0, 0, 0, 0, 0, 0, 0]])

array([0.01064069])