# 1. Введение

In [1]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [2]:
with open('result.txt', 'w') as f:
    f.write('5j')

In [3]:
with open('result.txt', 'r') as f:
    a = f.readline()
    print(a)

5j


# 2. Numpy
## 2.1 Основы

In [4]:
import numpy as np

In [5]:
np.__version__

'1.18.1'

### 2.1.1 Время кода

In [6]:
a = list(range(1_000_000))

In [7]:
%%timeit
[i*i for i in a]

145 ms ± 16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
b = np.arange(1_000_000)

In [9]:
%%timeit
b*b

2.96 ms ± 156 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### 2.1.2 Создание массива

In [10]:
d = np.asarray(a)
d

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [11]:
a = [1, 2, 3, 4, 5]
b = [6, 7, 8, 9, 10]
c = np.array([a,b], dtype=np.float64)
c

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [12]:
c.dtype

dtype('float64')

In [13]:
c.ndim

2

In [14]:
c.shape

(2, 5)

In [15]:
c.strides  # сколько битов отступить до следующего элемента

(40, 8)

In [16]:
res = c.reshape(-1, 2)  # -1 означает что numpy сам подберет подходящую размерность
res

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [17]:
v1 = res[2,0]
v2 = res[0][1]
print(v1, v2, sep="\n")

5.0
2.0


In [18]:
# вытягивание массива в одну строку
c = res.flatten()  # создает копию
res[0,1] = -22
c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
d = res.ravel()  # не создает копию
res[0,1] = -77
d

array([  1., -77.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [20]:
print(res, res.T, res.transpose(), res, sep="\n")  # трансонироание без копирования массива

[[  1. -77.]
 [  3.   4.]
 [  5.   6.]
 [  7.   8.]
 [  9.  10.]]
[[  1.   3.   5.   7.   9.]
 [-77.   4.   6.   8.  10.]]
[[  1.   3.   5.   7.   9.]
 [-77.   4.   6.   8.  10.]]
[[  1. -77.]
 [  3.   4.]
 [  5.   6.]
 [  7.   8.]
 [  9.  10.]]


### 2.1.3 Фиктивная ось - ось сразмерностью 1

In [21]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
b[np.newaxis,:]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
np.expand_dims(b, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [24]:
np.expand_dims(b, axis=1).shape

(10, 1)

In [25]:
b[np.newaxis,:,np.newaxis]

array([[[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]])

In [26]:
b[np.newaxis,:,np.newaxis].shape

(1, 10, 1)

### 2.1.4 Создание массивов с особыми свойствами

In [27]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
print(b)
np.zeros_like(b)

[0 1 2 3 4 5 6 7 8 9]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.ones(5)  # as np.ones(shape(5,))

array([1., 1., 1., 1., 1.])

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [32]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
np.linspace(0, 1, 5, endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8])

### 2.1.5 Избегаем ненужного копирования

In [34]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float32)
b = np.asarray(a) # указывает на данные а
c = np.array(a)   # создает копию данных из а

b, c

(array([1., 2., 3., 4., 5.], dtype=float32),
 array([1., 2., 3., 4., 5.], dtype=float32))

Но если создаем asarray из списка, то данные копируются

In [35]:
d = [1, 2, 3, 4, 5]
f = np.asarray(d)

d[0] = 66
d, f

([66, 2, 3, 4, 5], array([1, 2, 3, 4, 5]))

In [36]:
a[0] = 99
a, b, c

(array([99.,  2.,  3.,  4.,  5.], dtype=float32),
 array([99.,  2.,  3.,  4.,  5.], dtype=float32),
 array([1., 2., 3., 4., 5.], dtype=float32))

Но если поменять тип данных, то asarray скопирует данные

In [37]:
a = np.array([1, 2, 3, 4, 5], dtype=np.float32)
b = np.asarray(a, dtype=np.int32)
c = np.array(a) 

b, c

(array([1, 2, 3, 4, 5]), array([1., 2., 3., 4., 5.], dtype=float32))

In [38]:
a[0] = 23
a, b, c

(array([23.,  2.,  3.,  4.,  5.], dtype=float32),
 array([1, 2, 3, 4, 5]),
 array([1., 2., 3., 4., 5.], dtype=float32))

## 2.2 Поэлементные операции с массивами
### 2.2.1 Операции со скалярами и унарные операции

In [39]:
a = np.arange(10).reshape(2, -1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
a ** 3  # as np.power(a, 3)

array([[  0,   1,   8,  27,  64],
       [125, 216, 343, 512, 729]], dtype=int32)

In [41]:
a + 2  # as np.add(a, 2)

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [42]:
2 * a  # as np.multiply(2, a)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [43]:
2 ** a

array([[  1,   2,   4,   8,  16],
       [ 32,  64, 128, 256, 512]], dtype=int32)

In [44]:
np.multiply(2, a)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [45]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

In [46]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [47]:
np.log(1 + a)  # натуральный логарифм

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [48]:
np.log(np.e)

1.0

In [49]:
np.log2(1 + a)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809]])

In [50]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [51]:
a > 0

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

### 2.2.2 Агрегирующие операции

In [52]:
np.random.seed(5656)
a = np.random.randint(0, 30, size=(3, 2, 5))
a

array([[[20, 26, 22, 26,  7],
        [27,  2, 16, 19,  5]],

       [[ 1, 26, 19, 26,  9],
        [19,  2, 13, 22,  5]],

       [[28, 26,  5,  9,  5],
        [12,  9, 10, 22,  8]]])

In [53]:
a.min(), a.max(), a.argmax(), a.sum(), a.prod(), a.mean()

(1, 28, 20, 446, -922746880, 14.866666666666667)

In [54]:
np.min(a), np.max(a), np.argmax(a), np.sum(a), np.prod(a), np.mean(a)

(1, 28, 20, 446, -922746880, 14.866666666666667)

In [55]:
np.max(a, axis=0)

array([[28, 26, 22, 26,  9],
       [27,  9, 16, 22,  8]])

In [56]:
np.argmax(a)  # индекс в вытянутом массиве

20

In [57]:
np.ravel(a)[np.argmax(a)]

28

In [58]:
np.unravel_index(np.argmax(a), a.shape)  # индекс максимального в нашем массиве

(2, 0, 0)

### 2.2.3 Унарные операции над булевыми массивами

In [59]:
a = np.asarray([True, False, True, True, False])
a

array([ True, False,  True,  True, False])

In [60]:
a.any(), np.any(a), any(a)

(True, True, True)

In [61]:
a.all(), np.all(a), all(a)

(False, False, False)

In [62]:
a = np.asarray([[True, False, True, True, False],
              [True, True, True, True, False]])
a

array([[ True, False,  True,  True, False],
       [ True,  True,  True,  True, False]])

In [63]:
a.any(axis=0)

array([ True,  True,  True,  True, False])

In [64]:
a.all(axis=1)

array([False, False])

In [65]:
np.logical_not(a)

array([[False,  True, False, False,  True],
       [False, False, False, False,  True]])

In [66]:
~a

array([[False,  True, False, False,  True],
       [False, False, False, False,  True]])

### 2.2.4 Бинарные операции

In [67]:
a = a.astype(int)
a

array([[1, 0, 1, 1, 0],
       [1, 1, 1, 1, 0]])

In [68]:
np.random.seed(4968)

b = np.random.randint(0, 10, size=a.shape)
b

array([[3, 0, 8, 1, 3],
       [1, 0, 2, 7, 8]])

In [69]:
a + b

array([[4, 0, 9, 2, 3],
       [2, 1, 3, 8, 8]])

In [70]:
a

array([[1, 0, 1, 1, 0],
       [1, 1, 1, 1, 0]])

In [71]:
b

array([[3, 0, 8, 1, 3],
       [1, 0, 2, 7, 8]])

In [72]:
np.fmax(a,b)  # выбирает максимальное значение из каждого массива

array([[3, 0, 8, 1, 3],
       [1, 1, 2, 7, 8]])

In [73]:
a > b

array([[False, False, False, False, False],
       [False,  True, False, False, False]])

`ufunc` - универсальные <span style="background:orange; color:blue">функции<span>

In [74]:
np.random.seed(4968)

a = np.random.random(size=(2, 5))
b = a + np.random.random(size=(2, 5)) * 1e-5

In [75]:
a

array([[0.84899405, 0.47440119, 0.86248396, 0.52283505, 0.17836348],
       [0.95143319, 0.31661009, 0.52529329, 0.9555178 , 0.55391591]])

In [76]:
b

array([[0.84899953, 0.47440473, 0.86249356, 0.5228432 , 0.17836679],
       [0.95143742, 0.31661426, 0.52529758, 0.95552147, 0.55392037]])

In [77]:
np.isclose(a, b)  # хорошо сравнивать числа с плавающей точкой

array([[ True,  True, False, False, False],
       [ True, False,  True,  True,  True]])

In [78]:
np.allclose(a, b)

False

In [79]:
np.isclose(a, b).any()

True

In [80]:
1e-5

1e-05

### 2.2.5 Бинарные операции над булевыми массивами

In [82]:
a = np.asarray([True, True, False, False, True])
b = np.asarray([True, False, False, True, False])
a, b

(array([ True,  True, False, False,  True]),
 array([ True, False, False,  True, False]))

In [84]:
np.logical_and(a,b), np.logical_or(a,b), np.logical_xor(a,b)

(array([ True, False, False, False, False]),
 array([ True,  True, False,  True,  True]),
 array([False,  True, False,  True,  True]))

In [85]:
a & b, a | b, a ^ b  # битовые операции, в случае с bool эквиваленно строчке выше

(array([ True, False, False, False, False]),
 array([ True,  True, False,  True,  True]),
 array([False,  True, False,  True,  True]))

#### Правило приведения размерностей:
Предположим `a.shape = (a_1, a_2, ... , a_n)` и `b.shape = (b_1, b_2, ... , b_n)`
Тогда над массивами можно произвести поэлементную бинарную опреацию если:
+ a_i == b_i
- a_i == 1
* b_i == 1

## 2.3 Матричные операции над массивами

In [88]:
av = np.arange(1, 5).reshape(-1, 2)
av

array([[1, 2],
       [3, 4]])

In [89]:
bv = np.array([[1, 2], [-2, 1]])
bv

array([[ 1,  2],
       [-2,  1]])

In [90]:
av * bv  # Поэлементное перемножение

array([[ 1,  4],
       [-6,  4]])

In [92]:
np.matmul(av, bv)  # Матричное перемножение

array([[-3,  4],
       [-5, 10]])

In [93]:
np.dot(av, bv)  # Матричное перемножение как скалярное произведение между векторами

array([[-3,  4],
       [-5, 10]])

In [97]:
# Создание типа матрицы
am = np.matrix(av)  # данные копируются
bm = np.asmatrix(bv)  # ссылка на данные
am

matrix([[1, 2],
        [3, 4]])

In [98]:
#Тогда перемножение матричное
am * bm

matrix([[-3,  4],
        [-5, 10]])

In [102]:
# Возведение в степень матричное
am ** 2, am * am

(matrix([[ 7, 10],
         [15, 22]]),
 matrix([[ 7, 10],
         [15, 22]]))

## 2.4 Индексация
### 2.4.1 Индексация массивов

In [105]:
help(repr)

Help on built-in function repr in module builtins:

repr(obj, /)
    Return the canonical string representation of the object.
    
    For many object types, including most builtins, eval(repr(obj)) == obj.



In [106]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [109]:
variants = [a[0:5:1], a[0:5], a[:5]]
print(*map(repr,variants), sep="\n")

array([0, 1, 2, 3, 4])
array([0, 1, 2, 3, 4])
array([0, 1, 2, 3, 4])


Все элементы, стоящие на четных позициях

In [110]:
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

Все элементы, стоящие на НЕчетных позициях

In [111]:
a[1::2]

array([ 1,  3,  5,  7,  9, 11, 13])

### 2.4.2 Булева индексация (маски)

In [112]:
np.random.seed(42)
a = np.random.randint(-2, 7, 34)
a

array([ 4,  1,  5,  2,  4,  0,  4,  5,  2,  1,  5,  5,  0,  3,  2, -1,  5,
        3, -1,  2, -2,  3,  6, -2,  0,  4,  1,  6,  0,  2,  0,  4,  2,  6])

Найти все отрицательные элементы

In [113]:
a < 0  # маска

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
        True, False,  True, False, False,  True, False, False, False,
       False, False, False, False, False, False, False])

In [114]:
a[a < 0]

array([-1, -1, -2, -2])

Найти все элементы кратные трём

In [115]:
variants = [ a[a % 3 == 0], a[np.logical_not(a % 3)], a[~((a % 3).astype(bool))]]
print(*map(repr, variants), sep="\n")

array([0, 0, 3, 3, 3, 6, 0, 6, 0, 0, 6])
array([0, 0, 3, 3, 3, 6, 0, 6, 0, 0, 6])
array([0, 0, 3, 3, 3, 6, 0, 6, 0, 0, 6])


Найти все элементы кратные 3 или 5

In [116]:
mask_3 = a % 3 == 0
mask_5 = a % 5 == 0

variants = [a[np.logical_or(mask_3, mask_5)], a[mask_3 | mask_5]]
print(*map(repr, variants), sep="\n")

array([5, 0, 5, 5, 5, 0, 3, 5, 3, 3, 6, 0, 6, 0, 0, 6])
array([5, 0, 5, 5, 5, 0, 3, 5, 3, 3, 6, 0, 6, 0, 0, 6])


Найти все элементы кратные 2 и 3

In [118]:
mask_2 = a % 2 == 0
mask_3 = a % 3 == 0

variants = [a[np.logical_and(mask_2, mask_3)], a[mask_2 & mask_3], a[a % 6 == 0]]
print(*map(repr, variants), sep="\n")

array([0, 0, 6, 0, 6, 0, 0, 6])
array([0, 0, 6, 0, 6, 0, 0, 6])
array([0, 0, 6, 0, 6, 0, 0, 6])


### 2.4.3 Индексация в многомерных массивах

In [119]:
a = np.arange(30).reshape(5, -1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [120]:
# Плохой способ, происходит большое копирование данных
a[0][0], a[3][5]

(0, 23)

In [121]:
# Хороший способ
a[0,0], a[3,5]

(0, 23)

Получить строку с индексом 2

In [122]:
variants = [a[2], a[2,:]]
print(*map(repr, variants), sep="\n")

array([12, 13, 14, 15, 16, 17])
array([12, 13, 14, 15, 16, 17])


Получить столбец с идексом 3

In [123]:
a[:, 3]

array([ 3,  9, 15, 21, 27])

Получить все элементы, стоящие в первой строке и нечетных столбцах

In [124]:
a[0, 1::2]

array([1, 3, 5])

Получить строки, в которых есть хотя бы один 0

In [125]:
np.random.seed(42)
a = np.random.randint(-5, 5, size=(5,5))
a

array([[ 1, -2,  2, -1,  1],
       [ 4, -3,  1,  2, -1],
       [-2,  2,  2, -3,  0],
       [-1, -4,  2,  0, -4],
       [-1, -5,  4,  0,  3]])

In [127]:
a[(a == 0).any(axis=1), :]

array([[-2,  2,  2, -3,  0],
       [-1, -4,  2,  0, -4],
       [-1, -5,  4,  0,  3]])

Получить столбцы, в которых число положительных элементов больше числа отрицательных

In [128]:
a[:, (a > 0).sum(axis=0) > (a < 0).sum(axis=0)]

array([[2],
       [1],
       [2],
       [2],
       [4]])

Получить полжительные элеметы

In [131]:
a

array([[ 1, -2,  2, -1,  1],
       [ 4, -3,  1,  2, -1],
       [-2,  2,  2, -3,  0],
       [-1, -4,  2,  0, -4],
       [-1, -5,  4,  0,  3]])

In [132]:
a[a > 0]

array([1, 2, 1, 4, 1, 2, 2, 2, 2, 4, 3])

Получть индексы положительных элементов

In [133]:
np.where(a > 0)  # индескы

(array([0, 0, 0, 1, 1, 1, 2, 2, 3, 4, 4], dtype=int64),
 array([0, 2, 4, 0, 2, 3, 1, 2, 2, 2, 4], dtype=int64))

In [134]:
a[np.where(a > 0)]  # элементы

array([1, 2, 1, 4, 1, 2, 2, 2, 2, 4, 3])

In [143]:
np.vstack(np.where(a > 0)).T

array([[0, 0],
       [0, 2],
       [0, 4],
       [1, 0],
       [1, 2],
       [1, 3],
       [2, 1],
       [2, 2],
       [3, 2],
       [4, 2],
       [4, 4]], dtype=int64)

### 2.4.4 Fancy Indexing

In [144]:
a

array([[ 1, -2,  2, -1,  1],
       [ 4, -3,  1,  2, -1],
       [-2,  2,  2, -3,  0],
       [-1, -4,  2,  0, -4],
       [-1, -5,  4,  0,  3]])

Получить строки 2, 4, 3

In [146]:
a[[2,4,3],:]

array([[-2,  2,  2, -3,  0],
       [-1, -5,  4,  0,  3],
       [-1, -4,  2,  0, -4]])

Получить строки 2, 4, 3 в столбцах 0 и -1

In [153]:
a[np.ix_([2,4,3], [0,-1])]  # view, не копия

array([[-2,  0],
       [-1,  3],
       [-1, -4]])

In [154]:
a[[2,4,3],:][:,[0,-1]]  # копия

array([[-2,  0],
       [-1,  3],
       [-1, -4]])

### 2.4.5 Сокращенная индексация

In [155]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [156]:
a[..., 0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [159]:
a[0, ...], a[0, :, :]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [169]:
a[..., 0, :], a[:, 0, :]

(array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]))

## 2.5 Что еще есть полезного в numpy и scipy

### 2.5.1 Генерация случайных чисел

In [171]:
np.random.rand(10)  # случайные числа от 0 ло 1

array([0.04645041, 0.60754485, 0.17052412, 0.06505159, 0.94888554,
       0.96563203, 0.80839735, 0.30461377, 0.09767211, 0.68423303])

In [172]:
np.random.randint(0, 10, 10)  # целые числа

array([6, 7, 2, 0, 3, 1, 7, 3, 1, 5])

In [173]:
np.random.permutation(10)  # Перестановка из 10 элементов

array([0, 2, 6, 8, 7, 1, 4, 9, 3, 5])

In [175]:
np.random.choice(10, size=10)  # коллеция из 10 элементов, могут повторяться

array([8, 8, 0, 8, 6, 8, 7, 0, 7, 7])

### 2.5.2 Сортировка

In [176]:
np.random.seed(42)
a = np.random.choice(10, size=(3,10))
a

array([[6, 3, 7, 4, 6, 9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5, 4, 1, 7, 5, 1],
       [4, 0, 9, 5, 8, 0, 9, 2, 6, 3]])

In [177]:
np.sort(a.ravel())  # возвращает копию

array([0, 0, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 7,
       7, 7, 7, 7, 8, 9, 9, 9])

In [180]:
a.sort(axis=0)  # сортировка на месте
a

array([[3, 0, 7, 2, 5, 0, 1, 2, 5, 1],
       [4, 3, 7, 4, 6, 4, 2, 6, 6, 3],
       [6, 7, 9, 5, 8, 9, 9, 7, 7, 4]])

In [181]:
a.sort(axis=1)
a

array([[0, 0, 1, 1, 2, 2, 3, 5, 5, 7],
       [2, 3, 3, 4, 4, 4, 6, 6, 6, 7],
       [4, 5, 6, 7, 7, 7, 8, 9, 9, 9]])

In [188]:
np.random.seed(42)
a = np.random.choice(10, size=(3,10))
a

array([[6, 3, 7, 4, 6, 9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5, 4, 1, 7, 5, 1],
       [4, 0, 9, 5, 8, 0, 9, 2, 6, 3]])

In [189]:
a.argsort(axis=0)  # возвращает индексы отсортированного массива

array([[1, 2, 0, 1, 1, 2, 1, 2, 1, 1],
       [2, 0, 1, 0, 0, 1, 0, 0, 2, 2],
       [0, 1, 2, 2, 2, 0, 2, 1, 0, 0]], dtype=int64)

In [190]:
a.argsort(axis=1)

array([[6, 1, 3, 9, 0, 4, 7, 2, 8, 5],
       [6, 9, 3, 0, 5, 4, 8, 1, 2, 7],
       [1, 5, 7, 9, 0, 3, 8, 4, 2, 6]], dtype=int64)

### 2.5.3 Получение уникальных элементов

In [192]:
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2.5.4 Объенинение массиов

In [193]:
# from itertools import chain, zip_longest

In [197]:
np.random.seed(42)
c = np.random.permutation(np.arange(0, 12))
i = c.shape[0] // 2

a, b = c[:i], c[i:]
a, b = a.reshape(3, 2), b.reshape(3, 2)
a, b

(array([[10,  9],
        [ 0,  8],
        [ 5,  2]]),
 array([[ 1, 11],
        [ 4,  7],
        [ 3,  6]]))

In [199]:
np.vstack((a, b))  #вертикалая конкатанация

array([[10,  9],
       [ 0,  8],
       [ 5,  2],
       [ 1, 11],
       [ 4,  7],
       [ 3,  6]])

In [201]:
np.concatenate((a, b), axis=1)  #универсальная конкатанация

array([[10,  9,  1, 11],
       [ 0,  8,  4,  7],
       [ 5,  2,  3,  6]])

In [202]:
np.hstack((a, b))  #горизонтальная конкатанация

array([[10,  9,  1, 11],
       [ 0,  8,  4,  7],
       [ 5,  2,  3,  6]])

### 2.5.5 Подсчет расстояний между точками

In [203]:
from scipy.spatial.distance import pdist, squareform

In [204]:
np.random.seed(42)

X = np.random.random(size=(5, 2)) * 10
X # 5 точек например со значениями x и y

array([[3.74540119, 9.50714306],
       [7.31993942, 5.98658484],
       [1.5601864 , 1.5599452 ],
       [0.58083612, 8.66176146],
       [6.01115012, 7.08072578]])

In [205]:
d = pdist(X)  #массив расстояний который эффективно хранится в памяти
d

array([5.01713601, 8.24215491, 3.27553692, 3.31980708, 7.2642889 ,
       7.25066088, 1.70589385, 7.16902511, 7.09155104, 5.65579207])

In [207]:
squareform(d)  #расстояние между точками

array([[0.        , 5.01713601, 8.24215491, 3.27553692, 3.31980708],
       [5.01713601, 0.        , 7.2642889 , 7.25066088, 1.70589385],
       [8.24215491, 7.2642889 , 0.        , 7.16902511, 7.09155104],
       [3.27553692, 7.25066088, 7.16902511, 0.        , 5.65579207],
       [3.31980708, 1.70589385, 7.09155104, 5.65579207, 0.        ]])

In [208]:
norm  = np.linalg.norm(X, ord=2, axis=1)  #норма
norm

array([10.21830707,  9.45625249,  2.20626622,  8.68121432,  9.28819699])

In [210]:
squareform(pdist(X / norm[:, np.newaxis])) #нормированное расстояние

array([[0.        , 0.5044736 , 0.40732015, 0.30710853, 0.32711953],
       [0.5044736 , 0.        , 0.099751  , 0.79566899, 0.18113777],
       [0.40732015, 0.099751  , 0.        , 0.70316147, 0.0815713 ],
       [0.30710853, 0.79566899, 0.70316147, 0.        , 0.62621279],
       [0.32711953, 0.18113777, 0.0815713 , 0.62621279, 0.        ]])

In [212]:
pdist(X, metric='cosine')  #косинусная метрика, а была евклидова

array([0.12724681, 0.08295485, 0.04715783, 0.05350359, 0.00497513,
       0.31654457, 0.01640545, 0.24721802, 0.00332694, 0.19607123])